export const FETCH_QUOTES = "FETCH_QUOTES";
export const SELECT_CHARACTER = "SELECT_CHARACTER";
export const GET_RANDOM_QUOTE = "GET_RANDOM_QUOTE";
export const FETCH_EPISODES = "FETCH_EPISODES";
export const SELECT_EPISODE = "SELECT_EPISODE";
